### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: RespecWrath-UMM

### ISSUE THREAD

**Issue by Gyrados15** [BarleyFlour/RespecMod#229]
Righto so I updated the Game itself on Steam and then this mod to 1.10.17 but in the logs I'm getting this : 

[6/13 09:40:13][I] Found installed mod: D:\Steam Games\steamapps\common\Pathfinder Second Adventure\Mods\RespecWrath
[6/13 09:40:13][I] Respec Mod has no required modes.
[6/13 09:40:13][E] Failed to check installed mods.
[6/13 09:40:13][E] System.ArgumentException: An item with the same key has already been added. Key: RespecWrath-UMM
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at ModFinder.MainWindow.CheckInstalledModsInternal() in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 237

The previous version doesn't moan to me about duplicate keys.

**Comment by BarleyFlour** [comment]
I suspect you might have two versions of the mod in your Mods folder, you should try checking and making sure you only have one.

**Comment by Gyrados15** [comment]
Thanks for the tip! I went and fully deleted the old version then added the
new version and seems fine now
Kind Regards

Gary Shaw
